// Comprehensive entrance exam seed — upcoming + past results (last 18 months)
import pg from 'pg';
import { randomUUID } from 'crypto';
const { Pool } = pg;
const pool = new Pool({ connectionString: process.env.DATABASE_URL });

await pool.query('DELETE FROM "EntranceExam"');
console.log('Cleared existing exams');

const exams = [
  // ─── SCHOOL / BOARD EXAMS ─────────────────────────────────────────────
  {
    name: 'Tamil Nadu HSC (Class 12) Board Examination',
    shortName: 'TN HSC',
    conductedBy: 'Directorate of Government Examinations, Tamil Nadu',
    examType: 'School / Board',
    applicationStart: 'August 2025',
    applicationEnd: 'September 2025',
    examDate: 'March 2026',
    resultDate: 'May 2026',
    website: 'https://www.dge.tn.gov.in',
    description: 'Tamil Nadu Class 12 (Higher Secondary Certificate) board exam covering all streams — Science, Commerce, Arts. Marks used for TNEA and CUET admissions.',
    eligibility: 'Students appearing in Tamil Nadu State Board Class 12',
  },
  {
    name: 'Tamil Nadu SSLC (Class 10) Board Examination',
    shortName: 'TN SSLC',
    conductedBy: 'Directorate of Government Examinations, Tamil Nadu',
    examType: 'School / Board',
    applicationStart: 'August 2025',
    applicationEnd: 'September 2025',
    examDate: 'March 2026',
    resultDate: 'May 2026',
    website: 'https://www.dge.tn.gov.in',
    description: 'Tamil Nadu Class 10 Secondary School Leaving Certificate board examination. Gateway to HSC and diploma courses.',
    eligibility: 'Students appearing in Tamil Nadu State Board Class 10',
  },
  {
    name: 'CBSE Class 12 Board Examination',
    shortName: 'CBSE 12',
    conductedBy: 'Central Board of Secondary Education (CBSE)',
    examType: 'School / Board',
    applicationStart: 'October 2025',
    applicationEnd: 'November 2025',
    examDate: 'February–March 2026',
    resultDate: 'May 2026',
    website: 'https://cbse.gov.in',
    description: 'CBSE Class 12 board exam — the primary eligibility for JEE, NEET, CUET and all major professional entrance exams. Required 75% for IIT/NIT admission.',
    eligibility: 'Students registered with CBSE for Class 12',
  },
  {
    name: 'CBSE Class 10 Board Examination',
    shortName: 'CBSE 10',
    conductedBy: 'Central Board of Secondary Education (CBSE)',
    examType: 'School / Board',
    applicationStart: 'October 2025',
    applicationEnd: 'November 2025',
    examDate: 'February–March 2026',
    resultDate: 'May 2026',
    website: 'https://cbse.gov.in',
    description: 'CBSE Class 10 board exam — determines stream selection for Class 11/12. Good performance opens doors to science stream needed for JEE/NEET.',
    eligibility: 'Students registered with CBSE for Class 10',
  },
  {
    name: 'ISC Class 12 / ICSE Class 10 Examination',
    shortName: 'ICSE/ISC',
    conductedBy: 'Council for the Indian School Certificate Examinations (CISCE)',
    examType: 'School / Board',
    applicationStart: 'August 2025',
    applicationEnd: 'September 2025',
    examDate: 'February–March 2026',
    resultDate: 'May 2026',
    website: 'https://www.cisce.org',
    description: 'ICSE (Class 10) and ISC (Class 12) board exams conducted by CISCE. ISC marks are accepted for CUET and direct admission to many colleges.',
    eligibility: 'Students registered with CISCE',
  },

  // ─── OLYMPIAD / TALENT EXAMS ──────────────────────────────────────────
  {
    name: 'National Science Olympiad (NSO)',
    shortName: 'NSO',
    conductedBy: 'Science Olympiad Foundation (SOF)',
    examType: 'Olympiad / Talent',
    applicationStart: 'June 2025',
    applicationEnd: 'October 2025',
    examDate: 'November 2025 (Level 1)',
    resultDate: 'December 2025',
    website: 'https://www.sofworld.org/nso',
    description: 'School-level science olympiad for Classes 1–12. Tests physics, chemistry, biology concepts. Top performers go to Level 2 (national) and represent India internationally.',
    eligibility: 'School students Class 1 to 12',
  },
  {
    name: 'International Mathematics Olympiad (IMO)',
    shortName: 'IMO (SOF)',
    conductedBy: 'Science Olympiad Foundation (SOF)',
    examType: 'Olympiad / Talent',
    applicationStart: 'June 2025',
    applicationEnd: 'October 2025',
    examDate: 'November 2025 (Level 1)',
    resultDate: 'December 2025',
    website: 'https://www.sofworld.org/imo',
    description: 'School-level math olympiad for Classes 1–12. Tests mathematical reasoning, logical thinking and arithmetic. Top scorers qualify for Level 2 national round.',
    eligibility: 'School students Class 1 to 12',
  },
  {
    name: 'National Cyber Olympiad (NCO)',
    shortName: 'NCO',
    conductedBy: 'Science Olympiad Foundation (SOF)',
    examType: 'Olympiad / Talent',
    applicationStart: 'June 2025',
    applicationEnd: 'October 2025',
    examDate: 'November 2025',
    resultDate: 'December 2025',
    website: 'https://www.sofworld.org/nco',
    description: 'Tests computer science, coding, IT fundamentals for school students. Great preparation for future CS/IT students.',
    eligibility: 'School students Class 1 to 12',
  },
  {
    name: 'Indian Olympiad Qualifier in Mathematics (IOQM)',
    shortName: 'IOQM',
    conductedBy: 'Homi Bhabha Centre for Science Education (HBCSE)',
    examType: 'Olympiad / Talent',
    applicationStart: 'August 2025',
    applicationEnd: 'September 2025',
    examDate: 'January 2026',
    resultDate: 'February 2026',
    website: 'https://olympiads.hbcse.tifr.res.in',
    description: 'First stage of India\'s mathematical olympiad pathway leading to International Mathematical Olympiad (IMO). Replaces RMO+PRMO. Top scorers progress to INMO, then IMO training camp.',
    eligibility: 'Students of Class 8–12 below 20 years of age',
  },
  {
    name: 'National Standard Examination in Physics (NSEP)',
    shortName: 'NSEP',
    conductedBy: 'Indian Association of Physics Teachers (IAPT) / HBCSE',
    examType: 'Olympiad / Talent',
    applicationStart: 'July 2025',
    applicationEnd: 'September 2025',
    examDate: 'November 2025',
    resultDate: 'January 2026',
    website: 'https://olympiads.hbcse.tifr.res.in',
    description: 'First stage for International Physics Olympiad (IPhO). Top 300 students nationwide go to Indian National Physics Olympiad (INPhO), then Orientation Cum Selection Camp (OCSC).',
    eligibility: 'Students of Class 11–12 with PCM',
  },
  {
    name: 'National Standard Examination in Chemistry (NSEC)',
    shortName: 'NSEC',
    conductedBy: 'Indian Association of Physics Teachers (IAPT) / HBCSE',
    examType: 'Olympiad / Talent',
    applicationStart: 'July 2025',
    applicationEnd: 'September 2025',
    examDate: 'November 2025',
    resultDate: 'January 2026',
    website: 'https://olympiads.hbcse.tifr.res.in',
    description: 'First stage for International Chemistry Olympiad (IChO). Top students qualify for Indian National Chemistry Olympiad (INChO).',
    eligibility: 'Students of Class 11–12 with Chemistry',
  },
  {
    name: 'National Talent Search Examination (NTSE)',
    shortName: 'NTSE',
    conductedBy: 'NCERT',
    examType: 'Olympiad / Talent',
    applicationStart: 'August 2025',
    applicationEnd: 'September 2025',
    examDate: 'November 2025 (Stage 1 – State level)',
    resultDate: 'February 2026 (Stage 2 – National: May 2026)',
    website: 'https://ncert.nic.in/ntse.php',
    description: 'Premier scholarship exam for Class 10 students. 2000 scholarships awarded at ₹1250/month (Class 11–12) to ₹2000/month (UG/PG). Covers MAT + SAT (Scholastic Aptitude Test).',
    eligibility: 'Class 10 students — Stage 1 conducted by respective states/UTs',
  },
  {
    name: 'INSPIRE Scholarship for Higher Education (SHE)',
    shortName: 'INSPIRE-SHE',
    conductedBy: 'Department of Science and Technology (DST), Govt. of India',
    examType: 'Olympiad / Talent',
    applicationStart: 'July 2026',
    applicationEnd: 'October 2026',
    examDate: 'Merit-based (no exam)',
    resultDate: 'November 2026',
    website: 'https://online-inspire.gov.in',
    description: '₹80,000/year scholarship for students who scored in top 1% in Class 12 board exams and pursue natural sciences at UG level. No separate exam — based on board merit.',
    eligibility: 'Top 1% in Class 12 boards pursuing B.Sc/Integrated M.Sc in natural sciences',
  },

  // ─── UG ENGINEERING ENTRANCE ──────────────────────────────────────────
  {
    name: 'JEE Main 2026 – Session 1',
    shortName: 'JEE Main S1',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'UG Engineering',
    applicationStart: 'October 2025',
    applicationEnd: 'November 2025',
    examDate: 'January 2026',
    resultDate: 'February 2026',
    website: 'https://jeemain.nta.nic.in',
    description: 'Session 1 of JEE Main 2026. For admission to NITs, IIITs and GFTIs. Computer-based test with 75 questions (Physics, Chemistry, Maths). Best of two sessions considered for NIT/IIIT counselling.',
    eligibility: 'Class 12 pass or appearing; minimum 75% aggregate (65% for SC/ST)',
  },
  {
    name: 'JEE Main 2026 – Session 2',
    shortName: 'JEE Main S2',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'UG Engineering',
    applicationStart: 'January 2026',
    applicationEnd: 'February 2026',
    examDate: 'April 2026',
    resultDate: 'May 2026',
    website: 'https://jeemain.nta.nic.in',
    description: 'Session 2 of JEE Main 2026. Best percentile from Session 1 and Session 2 is used. Also gateway to JEE Advanced for IIT admission. Paper 2 for B.Arch and B.Planning.',
    eligibility: 'Class 12 pass or appearing; can attempt maximum 6 times over 3 years',
  },
  {
    name: 'JEE Advanced 2026',
    shortName: 'JEE Advanced',
    conductedBy: 'IIT Bombay (conducting IIT for 2026)',
    examType: 'UG Engineering – IITs',
    applicationStart: 'April 2026',
    applicationEnd: 'May 2026',
    examDate: 'May 2026',
    resultDate: 'June 2026',
    website: 'https://jeeadv.ac.in',
    description: 'Toughest engineering entrance exam — gateway to the 23 IITs. Two papers of 3 hours each. Only top 2.5 lakh JEE Main qualifiers are eligible. IIT Madras uses this for its BTech admissions.',
    eligibility: 'Top 2.5 lakh JEE Main qualifiers; max 2 attempts in consecutive years; below 25 years (30 for SC/ST)',
  },
  {
    name: 'Tamil Nadu Engineering Admissions (TNEA) 2026',
    shortName: 'TNEA',
    conductedBy: 'Anna University, Chennai',
    examType: 'UG Engineering',
    applicationStart: 'April 2026',
    applicationEnd: 'June 2026',
    examDate: 'No exam — merit-based on 12th marks',
    resultDate: 'July 2026 (Counselling)',
    website: 'https://tneaonline.org',
    description: 'Merit-based admission to all government and private engineering colleges in Tamil Nadu. Cutoff is out of 200 (Physics + Chemistry + Maths×2 / 4). Over 2 lakh seats across 500+ colleges.',
    eligibility: 'Class 12 with Physics, Chemistry, Maths. No entrance exam — purely merit-based',
  },
  {
    name: 'VIT Engineering Entrance Exam (VITEEE) 2026',
    shortName: 'VITEEE',
    conductedBy: 'VIT University',
    examType: 'UG Engineering',
    applicationStart: 'November 2025',
    applicationEnd: 'March 2026',
    examDate: 'April 2026 (Online, multiple slots)',
    resultDate: 'April 2026',
    website: 'https://viteee.vit.ac.in',
    description: 'Entrance for VIT Vellore, Chennai, AP and Bhopal campuses. Computer-based exam with 125 questions in Physics, Chemistry, Maths/Biology and English. About 2 lakh students appear annually.',
    eligibility: 'Class 12 with PCM or PCB; minimum 60% aggregate; top 7% in JEE Main also eligible for direct admission',
  },
  {
    name: 'SRM Joint Engineering Entrance Exam (SRMJEEE) 2026',
    shortName: 'SRMJEEE',
    conductedBy: 'SRM Institute of Science and Technology',
    examType: 'UG Engineering',
    applicationStart: 'November 2025',
    applicationEnd: 'March 2026',
    examDate: 'April 2026',
    resultDate: 'May 2026',
    website: 'https://www.srmist.edu.in/srmjeee',
    description: 'Entrance exam for SRM campuses in Kattankulathur (Chennai), Ramapuram, Vadapalani and other campuses. 125 MCQs — Physics, Chemistry, Maths/Biology, English. Online proctored exam.',
    eligibility: 'Class 12 with PCM/PCB; 60% aggregate in Class 11 & 12',
  },
  {
    name: 'Amrita Engineering Entrance Examination (AEEE) 2026',
    shortName: 'AEEE',
    conductedBy: 'Amrita Vishwa Vidyapeetham',
    examType: 'UG Engineering',
    applicationStart: 'November 2025',
    applicationEnd: 'March 2026',
    examDate: 'April 2026',
    resultDate: 'May 2026',
    website: 'https://www.amrita.edu/admissions/aeee',
    description: 'Entrance for Amrita campuses at Coimbatore, Chennai, Bengaluru, Kochi and Mysuru. 100 MCQs — Physics, Chemistry, Maths. JEE Main qualifiers with 80+ percentile get direct interview.',
    eligibility: 'Class 12 with Physics, Chemistry, Maths; 60% aggregate',
  },
  {
    name: 'Karunya Entrance Examination (KEE) 2026',
    shortName: 'KEE',
    conductedBy: 'Karunya Institute of Technology and Sciences',
    examType: 'UG Engineering',
    applicationStart: 'November 2025',
    applicationEnd: 'March 2026',
    examDate: 'April 2026',
    resultDate: 'May 2026',
    website: 'https://www.karunya.edu/kee',
    description: 'Entrance for Karunya University, Coimbatore. Physics, Chemistry, Maths. JEE/VITEEE/SRMJEEE scores also accepted.',
    eligibility: 'Class 12 with PCM; 60% aggregate',
  },
  {
    name: 'SASTRA School of Engineering Entrance Exam (SEEE) 2026',
    shortName: 'SASTRA SEEE',
    conductedBy: 'SASTRA Deemed University',
    examType: 'UG Engineering',
    applicationStart: 'December 2025',
    applicationEnd: 'April 2026',
    examDate: 'May 2026',
    resultDate: 'May 2026',
    website: 'https://www.sastra.edu/admissions',
    description: 'Entrance for SASTRA Deemed University, Thanjavur. Top JEE Main scorers and board toppers may get direct admission. MCQ-based — PCM syllabus.',
    eligibility: 'Class 12 with PCM; 60% aggregate',
  },
  {
    name: 'BITS Pilani Admission Test (BITSAT) 2026',
    shortName: 'BITSAT',
    conductedBy: 'Birla Institute of Technology and Science (BITS), Pilani',
    examType: 'UG Engineering',
    applicationStart: 'January 2026',
    applicationEnd: 'March 2026',
    examDate: 'May–June 2026',
    resultDate: 'July 2026',
    website: 'https://www.bits-pilani.ac.in/admissions/bitsat',
    description: 'Entrance for BITS Pilani, Goa and Hyderabad campuses. 130 questions — Physics, Chemistry, Maths, English & Logical Reasoning. 12th board toppers (class 1st in board) may get direct admission.',
    eligibility: 'Class 12 with PCM; minimum 75% in PCM separately; 12th appearing students only',
  },
  {
    name: 'National Aptitude Test in Architecture (NATA) 2026',
    shortName: 'NATA',
    conductedBy: 'Council of Architecture (CoA)',
    examType: 'UG Engineering',
    applicationStart: 'January 2026',
    applicationEnd: 'March 2026',
    examDate: 'April & June 2026 (Two tests)',
    resultDate: 'May & July 2026',
    website: 'https://www.nata.in',
    description: 'Compulsory for admission to B.Arch programs in all institutions except those under central universities. Tests drawing ability, aesthetic sensitivity and mathematical reasoning.',
    eligibility: 'Class 12 with Mathematics; minimum 50% aggregate',
  },
  {
    name: 'Common University Entrance Test (CUET) UG 2026',
    shortName: 'CUET UG',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'UG All Streams',
    applicationStart: 'February 2026',
    applicationEnd: 'March 2026',
    examDate: 'May 2026',
    resultDate: 'June 2026',
    website: 'https://cuet.samarth.ac.in',
    description: 'Single entrance for all central universities (Delhi, JNU, BHU, Hyderabad, etc.) and many state universities across all streams — Science, Commerce, Arts, Engineering, Law. Replaces individual DU/BHU entrance tests.',
    eligibility: 'Class 12 pass or appearing; domain subjects as per course applied',
  },

  // ─── UG MEDICAL ───────────────────────────────────────────────────────
  {
    name: 'National Eligibility cum Entrance Test (NEET) UG 2026',
    shortName: 'NEET UG',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'UG Medical / Dental',
    applicationStart: 'February 2026',
    applicationEnd: 'March 2026',
    examDate: 'May 2026',
    resultDate: 'June 2026',
    website: 'https://neet.nta.nic.in',
    description: 'Single entrance for all MBBS, BDS, BAMS, BHMS, BUMS and BSMS admissions across India including Madras Medical College, JIPMER, AIIMS. 720 marks (180 MCQs) — Physics, Chemistry, Biology.',
    eligibility: 'Class 12 with PCB; minimum 50% aggregate (40% for SC/ST/OBC/PwD); maximum 3 attempts',
  },

  // ─── LAW ──────────────────────────────────────────────────────────────
  {
    name: 'Common Law Admission Test (CLAT) 2026',
    shortName: 'CLAT',
    conductedBy: 'Consortium of National Law Universities',
    examType: 'UG Law',
    applicationStart: 'July 2025',
    applicationEnd: 'October 2025',
    examDate: 'December 2025',
    resultDate: 'January 2026',
    website: 'https://consortiumofnlus.ac.in',
    description: 'Entrance for the 24 National Law Universities (NLUs) including NLSIU Bangalore and NALSAR Hyderabad. 150 MCQs — English, Current Affairs, Legal Reasoning, Quantitative Techniques, Logical Reasoning.',
    eligibility: 'Class 12 with minimum 45% marks; no upper age limit',
  },

  // ─── PG / POSTGRADUATE ────────────────────────────────────────────────
  {
    name: 'Graduate Aptitude Test in Engineering (GATE) 2026',
    shortName: 'GATE 2026',
    conductedBy: 'IIT Kanpur (Organising Institute 2026)',
    examType: 'PG Engineering / MBA / MCA',
    applicationStart: 'August 2025',
    applicationEnd: 'October 2025',
    examDate: 'February 2026 (4 weekends)',
    resultDate: 'March 2026',
    website: 'https://gate2026.iitk.ac.in',
    description: 'Gateway for M.Tech/M.E admissions in IITs, NITs, IIITs and government colleges. Score also used by PSUs (BHEL, ONGC, NTPC, BARC) for direct recruitment. 29 subject papers available.',
    eligibility: 'Any branch of engineering/technology/architecture/science (final year or pass); no age limit',
  },
  {
    name: 'Tamil Nadu Common Entrance Test (TANCET) 2026',
    shortName: 'TANCET',
    conductedBy: 'Anna University, Chennai',
    examType: 'PG Engineering / MBA / MCA',
    applicationStart: 'January 2026',
    applicationEnd: 'February 2026',
    examDate: 'March 2026',
    resultDate: 'April 2026',
    website: 'https://www.annauniv.edu/tancet',
    description: 'Entrance for M.E, M.Tech, MBA, MCA, M.Arch admissions in Tamil Nadu government and private colleges. Separate papers for each stream. Mandatory for all government/aided college PG seats.',
    eligibility: 'BE/B.Tech for M.E/M.Tech; Any degree for MBA; B.Sc/BCA/BCS for MCA',
  },
  {
    name: 'Common Admission Test (CAT) 2025',
    shortName: 'CAT 2025',
    conductedBy: 'IIMs (IIM Ahmedabad for 2025)',
    examType: 'PG Engineering / MBA / MCA',
    applicationStart: 'July 2025',
    applicationEnd: 'September 2025',
    examDate: 'November 2025',
    resultDate: 'January 2026',
    website: 'https://iimcat.ac.in',
    description: 'Premier MBA entrance for admission to IIMs (Ahmedabad, Bangalore, Calcutta, etc.) and 1200+ management institutions. 66 questions — Verbal Ability, Data Interpretation, Quantitative Aptitude. 40 lakh+ candidates apply.',
    eligibility: 'Any bachelor\'s degree with 50% aggregate (45% for SC/ST/PwD)',
  },
  {
    name: 'Xavier Aptitude Test (XAT) 2026',
    shortName: 'XAT 2026',
    conductedBy: 'XLRI Jamshedpur',
    examType: 'PG Engineering / MBA / MCA',
    applicationStart: 'July 2025',
    applicationEnd: 'November 2025',
    examDate: 'January 2026',
    resultDate: 'January 2026',
    website: 'https://xatonline.in',
    description: 'Entrance for XLRI, XIM, and 200+ management institutions. Unique for its Decision Making section. 250+ colleges accept XAT scores including XIMB, TAPMI, Great Lakes Chennai.',
    eligibility: 'Any bachelor\'s degree (final year also eligible)',
  },
  {
    name: 'Management Aptitude Test (MAT) 2025',
    shortName: 'MAT',
    conductedBy: 'All India Management Association (AIMA)',
    examType: 'PG Engineering / MBA / MCA',
    applicationStart: 'Ongoing (multiple sessions)',
    applicationEnd: 'Ongoing',
    examDate: 'September, December 2025 & February 2026',
    resultDate: 'Within 30 days of exam',
    website: 'https://mat.aima.in',
    description: 'Accepted by 600+ MBA colleges. Conducted 4 times a year (February, May, September, December). Available in Paper-Based Test (PBT), Computer-Based Test (CBT) and Internet-Based Test (IBT) modes.',
    eligibility: 'Any bachelor\'s degree; final year students also eligible',
  },
  {
    name: 'Common Management Admission Test (CMAT) 2026',
    shortName: 'CMAT',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'PG Engineering / MBA / MCA',
    applicationStart: 'February 2026',
    applicationEnd: 'March 2026',
    examDate: 'May 2026',
    resultDate: 'June 2026',
    website: 'https://cmat.nta.nic.in',
    description: 'NTA-conducted MBA entrance accepted by AICTE-approved institutes. 100 MCQs — Quantitative Techniques, Logical Reasoning, Language Comprehension, General Awareness, Innovation & Entrepreneurship.',
    eligibility: 'Any bachelor\'s degree; final year students eligible',
  },
  {
    name: 'NEET PG 2026',
    shortName: 'NEET PG',
    conductedBy: 'National Board of Examinations (NBE)',
    examType: 'PG Medical',
    applicationStart: 'February 2026',
    applicationEnd: 'March 2026',
    examDate: 'June 2026',
    resultDate: 'July 2026',
    website: 'https://natboard.edu.in',
    description: 'Single entrance for all MD/MS/Diploma postgraduate medical admissions in India. 200 questions — MCQ based; all clinical and pre-clinical subjects of MBBS. 50,000+ PG medical seats.',
    eligibility: 'MBBS with compulsory rotating internship completed; no upper age limit',
  },

  // ─── DEFENCE ──────────────────────────────────────────────────────────
  {
    name: 'National Defence Academy (NDA) Examination I – 2026',
    shortName: 'NDA I 2026',
    conductedBy: 'Union Public Service Commission (UPSC)',
    examType: 'Defence',
    applicationStart: 'December 2025',
    applicationEnd: 'January 2026',
    examDate: 'April 2026',
    resultDate: 'June 2026 (Written); SSB in August 2026',
    website: 'https://upsc.gov.in',
    description: 'Entry to National Defence Academy (Army, Navy, Air Force wings). Written exam: Maths (300) + General Ability (600) = 900 marks. Followed by SSB interview. Leads to commission in Indian Armed Forces after 3-year training.',
    eligibility: 'Class 12 pass or appearing; Male/Female; 16.5 to 19.5 years; unmarried',
  },
  {
    name: 'National Defence Academy (NDA) Examination II – 2026',
    shortName: 'NDA II 2026',
    conductedBy: 'Union Public Service Commission (UPSC)',
    examType: 'Defence',
    applicationStart: 'May 2026',
    applicationEnd: 'June 2026',
    examDate: 'September 2026',
    resultDate: 'November 2026',
    website: 'https://upsc.gov.in',
    description: 'Second NDA exam of 2026. Same pattern — Maths (300) + General Ability (600). SSB interview for written qualifiers. Navy/Air Force require PCM in Class 12.',
    eligibility: 'Class 12 pass or appearing; 16.5 to 19.5 years; unmarried',
  },
  {
    name: 'Combined Defence Services (CDS) Examination I – 2026',
    shortName: 'CDS I 2026',
    conductedBy: 'Union Public Service Commission (UPSC)',
    examType: 'Defence',
    applicationStart: 'October 2025',
    applicationEnd: 'November 2025',
    examDate: 'February 2026',
    resultDate: 'April 2026',
    website: 'https://upsc.gov.in',
    description: 'Entry for IMA, INA, AFA and OTA. For IMA/Navy/Air Force: English + General Knowledge + Elementary Mathematics (100 marks each). For OTA: English + General Knowledge only. Requires graduation.',
    eligibility: 'Graduation in any stream; age 20–24 (IMA/Navy/Air Force) or 19–25 (OTA)',
  },

  // ─── PAST RESULTS (Last 18 months — students can check scores) ────────
  {
    name: 'JEE Main 2025 – Session 1 (Results Available)',
    shortName: 'JEE Main 2025 S1',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'Past Results',
    applicationStart: 'Oct 2024',
    applicationEnd: 'Nov 2024',
    examDate: 'January 2025',
    resultDate: 'February 2025 ✓ Results Declared',
    website: 'https://jeemain.nta.nic.in',
    description: 'JEE Main 2025 Session 1 results are declared. Check your scorecard, percentile and category rank on the NTA portal. Use CRL rank for NIT/IIIT counselling.',
    eligibility: 'Check results at jeemain.nta.nic.in using application number and date of birth',
  },
  {
    name: 'JEE Main 2025 – Session 2 (Results Available)',
    shortName: 'JEE Main 2025 S2',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'Past Results',
    applicationStart: 'Jan 2025',
    applicationEnd: 'Feb 2025',
    examDate: 'April 2025',
    resultDate: 'May 2025 ✓ Results Declared',
    website: 'https://jeemain.nta.nic.in',
    description: 'JEE Main 2025 Session 2 results declared. Best percentile from Session 1 and Session 2 used for JoSAA counselling. JEE Advanced 2025 eligibility list also released based on combined performance.',
    eligibility: 'Check results at jeemain.nta.nic.in',
  },
  {
    name: 'JEE Advanced 2025 (Results Available)',
    shortName: 'JEE Advanced 2025',
    conductedBy: 'IIT Roorkee',
    examType: 'Past Results',
    applicationStart: 'Apr 2025',
    applicationEnd: 'May 2025',
    examDate: 'May 2025',
    resultDate: 'June 2025 ✓ Results Declared',
    website: 'https://jeeadv.ac.in',
    description: 'JEE Advanced 2025 results declared. AIR rank list published. IIT JoSAA counselling rounds completed. Check your rank, subject-wise scores and AAT qualifying status on the official portal.',
    eligibility: 'Check results at jeeadv.ac.in using registration number and date of birth',
  },
  {
    name: 'NEET UG 2025 (Results Available)',
    shortName: 'NEET UG 2025',
    conductedBy: 'National Testing Agency (NTA)',
    examType: 'Past Results',
    applicationStart: 'Feb 2025',
    applicationEnd: 'Mar 2025',
    examDate: 'May 2025',
    resultDate: 'June 2025 ✓ Results Declared',
    website: 'https://neet.nta.nic.in',
    description: 'NEET UG 2025 results declared. AIR rank, category rank, and percentile available. MCC counselling for government medical colleges and state counselling for Tamil Nadu seats (MBBS at Madras Medical College etc.) completed.',
    eligibility: 'Check scorecard at neet.nta.nic.in',
  },
  {
    name: 'GATE 2025 (Results Available)',
    shortName: 'GATE 2025',
    conductedBy: 'IIT Roorkee (Organising Institute)',
    examType: 'Past Results',
    applicationStart: 'Aug 2024',
    applicationEnd: 'Oct 2024',
    examDate: 'February 2025',
    resultDate: 'March 2025 ✓ Results Declared',
    website: 'https://gate2025.iitr.ac.in',
    description: 'GATE 2025 results declared. Scorecard valid for 3 years. Use for M.Tech admissions at IITs, NITs including NIT Trichy. PSU companies (BHEL, ONGC, BARC) also recruiting based on GATE 2025 scores.',
    eligibility: 'Download scorecard at gate2025.iitr.ac.in',
  },
  {
    name: 'TANCET 2025 (Results Available)',
    shortName: 'TANCET 2025',
    conductedBy: 'Anna University, Chennai',
    examType: 'Past Results',
    applicationStart: 'Jan 2025',
    applicationEnd: 'Feb 2025',
    examDate: 'March 2025',
    resultDate: 'April 2025 ✓ Results Declared',
    website: 'https://www.annauniv.edu/tancet',
    description: 'TANCET 2025 results available on Anna University official website. Rank list for M.E, M.Tech, MBA, MCA counselling at Tamil Nadu government and aided colleges.',
    eligibility: 'Check results at annauniv.edu/tancet',
  },
  {
    name: 'TNEA 2025 (Counselling Completed)',
    shortName: 'TNEA 2025',
    conductedBy: 'Anna University, Chennai',
    examType: 'Past Results',
    applicationStart: 'Apr 2025',
    applicationEnd: 'Jun 2025',
    examDate: 'Merit-based',
    resultDate: 'August 2025 ✓ Allotment Completed',
    website: 'https://tneaonline.org',
    description: 'TNEA 2025 seat allotment completed. Students who received allotment have joined colleges. Spot admissions and management quota seats may still be available at some private colleges.',
    eligibility: 'Check allotment status at tneaonline.org',
  },
  {
    name: 'CAT 2024 (Results Available)',
    shortName: 'CAT 2024',
    conductedBy: 'IIMs (IIM Calcutta for 2024)',
    examType: 'Past Results',
    applicationStart: 'Aug 2024',
    applicationEnd: 'Sep 2024',
    examDate: 'November 2024',
    resultDate: 'January 2025 ✓ Results Declared',
    website: 'https://iimcat.ac.in',
    description: 'CAT 2024 results declared. IIM shortlists and calls issued. Results valid for admission to IIMs and 1200+ B-schools for academic year 2025-26. Check percentile and section-wise scores at official portal.',
    eligibility: 'Check results at iimcat.ac.in',
  },
  {
    name: 'TN HSC 2025 Results (12th Board)',
    shortName: 'TN HSC 2025',
    conductedBy: 'Directorate of Government Examinations, Tamil Nadu',
    examType: 'Past Results',
    applicationStart: 'Aug 2024',
    applicationEnd: 'Sep 2024',
    examDate: 'March 2025',
    resultDate: 'May 2025 ✓ Results Declared',
    website: 'https://www.dge.tn.gov.in',
    description: 'Tamil Nadu HSC (Class 12) 2025 results declared. Marks used for TNEA 2025 counselling. Check results at dge.tn.gov.in with your register number. Toppers list also published.',
    eligibility: 'Check at dge.tn.gov.in or tnresults.nic.in',
  },
];

const values = exams.map(e =>
  `('${randomUUID()}', '${e.name.replace(/'/g,"''")}', '${e.shortName.replace(/'/g,"''")}', '${e.conductedBy.replace(/'/g,"''")}', '${e.examType}', '${e.applicationStart}', '${e.applicationEnd}', '${e.examDate.replace(/'/g,"''")}', '${e.resultDate.replace(/'/g,"''")}', '${e.website}', '${e.description.replace(/'/g,"''")}', '${e.eligibility.replace(/'/g,"''")}', NOW())`
).join(',\n');

await pool.query(`INSERT INTO "EntranceExam" (id,name,"shortName","conductedBy","examType","applicationStart","applicationEnd","examDate","resultDate",website,description,eligibility,"createdAt") VALUES ${values}`);

console.log(`Inserted ${exams.length} exams`);
await pool.end();
